[package]
name = "shork"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shork-error = {path = "../error"}
shork-lexer = {path = "../lexer"}
shork-parser = {path = "../parser"}